### ISSUE TITLE
[FEATURE] setLoop

### ISSUE THREAD

**Issue by ggdream** [alexmercerind/dart_vlc#169]
Request to implement the `setLoop` API, how do I implement automatic loop playback now?

**Comment by alexmercerind** [comment]
This feature is already in the plugin. Just make sure to open a `Playlist` in `Player.open`.

https://github.com/alexmercerind/dart_vlc/blob/d13d06e5e4f1536e6a533c5657793390d78f10d0/ffi/lib/src/player.dart#L262-L268

https://github.com/alexmercerind/dart_vlc/blob/d13d06e5e4f1536e6a533c5657793390d78f10d0/ffi/lib/src/enums/playlistMode.dart#L1-L11

Feel free to let me know if I'm missing something. Otherwise close the issue.
Thanks.

**Comment by ggdream** [comment]
> This feature is already in the plugin. Just make sure to open a `Playlist` in `Player.open`.
> 
> https://github.com/alexmercerind/dart_vlc/blob/d13d06e5e4f1536e6a533c5657793390d78f10d0/ffi/lib/src/player.dart#L262-L268
> 
> https://github.com/alexmercerind/dart_vlc/blob/d13d06e5e4f1536e6a533c5657793390d78f10d0/ffi/lib/src/enums/playlistMode.dart#L1-L11
> 
> Feel free to let me know if I'm missing something. Otherwise close the issue. Thanks.
> 
> There are a lot of features that I add, but forget to document in the README.



> This feature is already in the plugin. Just make sure to open a `Playlist` in `Player.open`.
> 
> https://github.com/alexmercerind/dart_vlc/blob/d13d06e5e4f1536e6a533c5657793390d78f10d0/ffi/lib/src/player.dart#L262-L268
> 
> https://github.com/alexmercerind/dart_vlc/blob/d13d06e5e4f1536e6a533c5657793390d78f10d0/ffi/lib/src/enums/playlistMode.dart#L1-L11
> 
> Feel free to let me know if I'm missing something. Otherwise close the issue. Thanks.
> 
> There are a lot of features that I add, but forget to document in the README.

That's it, thank you very much for your reply!
