### ISSUE TITLE
Hardware Acceleration

### ISSUE THREAD

**Issue by dennis9352** [alexmercerind/dart_vlc#258]
your ```dart_vlc``` ran beautifully in my desktop having little decent specification but when I tried in cpu with only integrated graphics, the cpu consumption became too high. I think It would be so much useful if there is hardware acceleration/GPU acceleration option.

**Comment by alexmercerind** [comment]
See details given at #254. I have well documented current situation there. It's not limitation in a `dart_vlc`.

Also, please consider opening a discussion if you feel like your issue doesn't match any of the existing issue templates.
Thanks.

**Comment by alexmercerind** [comment]
Copying relevant details here for future visitors.

<hr></hr>

Vanilla [`Video`](https://github.com/alexmercerind/dart_vlc#show-the-video-inside-widget-tree) widget uses `libvlc_video_set_callbacks` (best as-of libvlc 3.0) which has performance-costs at higher resolution videos due to pixel-buffer (RGBA/BGRA depending upon platform) conversion & other copy operations when using `Texture` widget. libvlc 4.0 will come with a better rendering API which supports rendering into an OpenGL context or Direct3D device/surface.
STILL, on Flutter Windows, there are no GPU-backed-buffers for `Texture` widget. So, there is no way around it.

The new [`NativeVideo`](https://github.com/alexmercerind/dart_vlc#nativevideo) widget on the other hand, uses [`flutter_native_view`](https://github.com/alexmercerind/flutter_native_view) on Windows currently (in future, I will add Linux support myself). On other platforms, official platform views can be used.
In general, [`NativeVideo`](https://github.com/alexmercerind/dart_vlc#nativevideo) is more-performant since it doesn't involve any pixel-buffer conversion, neither unnecessary copy operations. A native VLC-video-output window is directly embedded inside Flutter view as a `Widget`.

|[`NativeVideo`](https://github.com/alexmercerind/dart_vlc#nativevideo) (NEWER)|[`Video`](https://github.com/alexmercerind/dart_vlc#show-the-video-inside-widget-tree) (OLDER)|
|---------------|--------|
|![native_video](https://user-images.githubusercontent.com/28951144/162476283-bf5e7a71-2248-47e4-87b6-54670dc9bf39.png)|![video](https://user-images.githubusercontent.com/28951144/162475702-306f605b-9906-4929-a333-eea555c5c639.png)|

_[Video: 1080p 60FPS 4973kbps. CPU: AMD Ryzen 3 2200U (ZEN I). GPU: AMD Radeon Vega 3 (Integrated)]_
_On normal 720p videos, both CPU & GPU usages stay around ~5% on [`NativeVideo`](https://github.com/alexmercerind/dart_vlc#nativevideo) & bearable on [`Video`](https://github.com/alexmercerind/dart_vlc#show-the-video-inside-widget-tree)._
