### ISSUE TITLE
Question about the implementation principle

### ISSUE THREAD

**Issue by lycstar** [alexmercerind/dart_vlc#27]
I looked at the source code and found that you decoded the video with vlc, then passed data through the platform channel, and finally rendered through RawImage. Am I right? Will there be a performance problem? Is there any better way?

**Comment by alexmercerind** [comment]
Hi @lycstar !

Current implementation extracts RAW frame and sends back it to Dart through platform channel for rendering it using `RawImage` and `decodeImageFromPixels`.
For more detail, a single buffer is allocated on the heap of size videoHeight * videoWidth * 4 bytes as `uint8_t[]` in which frame data is stored. Recently its been informed to me ((here)[https://github.com/alexmercerind/dart_vlc/issues/24]), that the data sent through platform channels is being retained in memory & seems a new buffer is being allocated everytime (maybe some deepcopying is happening somewhere). So, it needs to be figured out by me first of all as a priority.

You are exactly right, this isn't the best in terms of performance but I don't think there is anything else we can do for showing a video inside Widget tree. Even official video_player plugin does so. Although, it is hard on CPU & does not use GPU.

A native viewport directly from libVLC  will be shown if you pass `videoHeight` and `videoWidth` as 0, while instantiating `Player` class. But it will be a separate window & will not be shown inside Widget tree. This native viewport is more performant as its direct libVLC doing its thing & is GPU accelerated.

Apart from all above, I've started to work on FFI based implementation of this plugin so that I can bring this library to Android or mac or console dart applications. Considering that, there will be no need to transfer frame data in that case for console apps.\


Thanks.
I'll be willing to improve the implementation, but I believe showing RAW frames is the best that we can have right now.

**Comment by alexmercerind** [comment]
The memory leak issue is fixed & considering its a question, I feel my answer gives you enough reasoning of things.

**Comment by lycstar** [comment]
@alexmercerind Thank you for your anwser.
