### ISSUE TITLE
[Platform Speific] Allow us to target platforms

### ISSUE THREAD

**Issue by ollydixon** [alexmercerind/dart_vlc#294]
Allow us to drop support for iOS/MacOS. We have a use case where we want to use this library for Windows only.

I forked the library but it's unclear how I can drop support for other platforms. We use another video player for iOS/Android/Web/MacOS.

@alexmercerind thanks for making and supporting the library, good work!

:-)

**Comment by GroovinChip** [comment]
@ollydixon in order to drop support for a platform you have to:
1) Delete the platform's "runner" at the plugin level
![image](https://user-images.githubusercontent.com/4250470/175043655-ac73964c-1994-43cb-95c3-853d43bd25dd.png)
2) Delete the platform's entry in the `plugin` level of the `flutter` section of the `pubspec.yaml` file.
![image](https://user-images.githubusercontent.com/4250470/175043888-b5548b61-3769-4b08-81fb-f1681063b292.png)
These steps will ensure that macOS support is removed from your fork.

**Comment by ollydixon** [comment]
@GroovinChip I did this but it still throws build errors on those platforms.

**Comment by ollydixon** [comment]
@GroovinChip I kept facing complication errors, even when removing the reference to other platforms :-/

**Comment by GroovinChip** [comment]
Is the error a build error or a runtime error?

**Comment by GroovinChip** [comment]
For which platforms

**Comment by ollydixon** [comment]
@GroovinChip I said in the ticket, iOS/MacOS. As they already have video players now; we only really need a Windows one now.

**Comment by imtoori** [comment]
I can confirm it works fine on `master`
