### ISSUE TITLE
PlayList.playlistMode is ignored by Player.open()

### ISSUE THREAD

**Issue by andrew-tpz** [alexmercerind/dart_vlc#315]
Expected to work, but it doesn't:
```
      player.open(
        Playlist(
          medias: medias,
          playlistMode: PlaylistMode.loop,
        ),
      );
```

Workaround:
```
      player
        ..setPlaylistMode(PlaylistMode.loop)
        ..open(
          Playlist(
            medias: medias,
          ),
        );
```

**Comment by alexmercerind** [comment]
Hi @andrew-tpz!

I have decided to remove the `playlistMode` argument from the `Playlist` class.

During the days of development, `package:dart_vlc` received a major re-write to use FFI instead of platform channels.
Somehow, I forgot to handle this optional argument in native-code.

From an API standpoint, I feel this to be redundant now.
Having `setPlaylistMode` method on `Player` class itself is more than enough & works correctly.

Thanks!
