### ISSUE TITLE
Windows NativeVideo not supported Fit

### ISSUE THREAD

**Issue by Srn5333** [alexmercerind/dart_vlc#337]

**Comment by alexmercerind** [comment]
Hi @filly82, I have decided to remove `NativeVideo` widget for now in the latest version v0.4.0. Since it is no more, this is no longer a concern. Below I have discussed the future plans:

First of all, sorry for being inactive. I've been occupied with my exams & college. Maintaining open-source packages requires consistent work & time out of daily life. Writing C++ & native code is even more tedious.

There are a number of issues with this package, both in regard of performance & stability which I would like to fix. I'm not quite satisfied with the current state of the package, though I believe it is still usable. Hardware acceleration is a big concern. Currently, a substantial amount of load is caused on the CPU when using package:dart_vlc. This is because every video frame is copied from GPU to RAM buffer (which is a CPU process & CPU isn't made for rendering) for drawing it into Flutter's texture widget, both due to Flutter & libvlc's limitations at that time.

Now, my work is sponsored by [Stream](https://getstream.io/chat/sdk/flutter/?utm_source=alexmercerind_dart&utm_medium=Github_Repo_Content_Ad&utm_content=Developer&utm_campaign=alexmercerind_December2022_FlutterSDK_klmh22).
I can now proceed my work with peace & build the best-ever performant & stable video library for Flutter Desktop.

Thanks!
