### ISSUE TITLE
Window is black when using NativeVideo

### ISSUE THREAD

**Issue by albrrt** [alexmercerind/dart_vlc#338]
I am trying to play a H264 video from the assets folder using Native Video.
The playbar is progressing but the screen is black. However, if I click on play button again after it finishes playing once, it opens up a new window called "VLC (Direct3D output)" and I can see the video playing well there. 

This is true if I use Media.file(...) or Media.asset(...) constructor.

I need the video to play in the original window from the start. 

```
import 'package:dart_vlc/dart_vlc.dart';
import 'package:flutter/material.dart';

Future<void> main() async {
  await DartVLC.initialize(useFlutterNativeView: true);
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final videoPlayer = Player(id: 6940);

  @override
  void initState() {
    super.initState();
    videoPlayer.open(Media.asset("assets/videos/Circus.mp4"));
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Native Video Test',
        home: Scaffold(
            body: NativeVideo(
                showControls: true,
                player: videoPlayer,
                width: 1920,
                height: 1080)));
  }
}
```

flutter doctor --verbose
```
[√] Flutter (Channel stable, 3.3.2, on Microsoft Windows [Version 10.0.19044.2130], locale en-GB)
    • Flutter version 3.3.2 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (5 weeks ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32901.215
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.72.2)
    • VS Code at C:\Users\<username>\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.50.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.2130]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 103.0.5060.134
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 106.0.1370.47

[√] HTTP Host Availability
    • All required HTTP hosts are available
```

**Operating system:**
- Platform: Windows
- OS version: 10.0.19044 Build 19044

**Other details:**
- [x] I confirm this is not a bug in the VLC app & only `dart_vlc`.
- [ ] I have donated / sponsored `dart_vlc`.

**Screenshots**

![double-Window](https://user-images.githubusercontent.com/28485330/197005248-86c9eb96-0d2b-4b73-a425-70a8b1f0633c.png)

Possibly related to #275

**Comment by j787701730** [comment]
https://github.com/alexmercerind/flutter_native_view
![image](https://user-images.githubusercontent.com/23625690/199866768-ce3acb95-2a28-4543-9be4-fbd5e35690e0.png)

**Comment by alexmercerind** [comment]
Hi @filly82, I have decided to remove `NativeVideo` widget for now in the latest version v0.4.0. Since it is no more, this is no longer a concern. Below I have discussed the future plans:

First of all, sorry for being inactive. I've been occupied with my exams & college. Maintaining open-source packages requires consistent work & time out of daily life. Writing C++ & native code is even more tedious.

There are a number of issues with this package, both in regard of performance & stability which I would like to fix. I'm not quite satisfied with the current state of the package, though I believe it is still usable. Hardware acceleration is a big concern. Currently, a substantial amount of load is caused on the CPU when using package:dart_vlc. This is because every video frame is copied from GPU to RAM buffer (which is a CPU process & CPU isn't made for rendering) for drawing it into Flutter's texture widget, both due to Flutter & libvlc's limitations at that time.

Now, my work is sponsored by [Stream](https://getstream.io/chat/sdk/flutter/?utm_source=alexmercerind_dart&utm_medium=Github_Repo_Content_Ad&utm_content=Developer&utm_campaign=alexmercerind_December2022_FlutterSDK_klmh22).
I can now proceed my work with peace & build the best-ever performant & stable video library for Flutter Desktop.

Thanks!

**Comment by hongfeiyucode** [comment]
> https://github.com/alexmercerind/flutter_native_view ![image](https://user-images.githubusercontent.com/23625690/199866768-ce3acb95-2a28-4543-9be4-fbd5e35690e0.png)

Have you solved the problem of dart_vlc accelerating black screen in NativeVideo hardware?
