### ISSUE TITLE
Error building on Linux

### ISSUE THREAD

**Issue by isaacclinton** [alexmercerind/dart_vlc#353]
# Error Building on Linux 
## Description
I get the following error when trying to run a project with dart_vlc as the only external plugin.
```
/home/user/project/linux/flutter/ephemeral/.plugin_symlinks/dart_vlc/core/api/api.cc:43:48:  
warning: cannot delete expression with pointer-to-'void' type 'void *' [-Wdelete-incomplete]
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
## Platform
dart_vlc version: 0.4.0
Operating System - Ubuntu 20.04
Flutter SDK version - 3.3.10

**Comment by alexmercerind** [comment]
It's called warning not error.

The error is linking issue not compiling issue, which is because you:
- [didn't read documentation correctly](https://github.com/alexmercerind/dart_vlc#setup).
- don't know how linux packages works.

Next time, share logs with `--verbose` flag. I can't comprehend how did you think those 2 lines contain anything useful.
If there was any issue, the CI would've been failing.
