### ISSUE TITLE
[Docs] Clarification on PlaylistMode

### ISSUE THREAD

**Issue by GZGavinZhao** [alexmercerind/dart_vlc#87]
Not sure if this is because English is not my native language, but I'm completely confused about the differences between the [`PlaylistMode`](https://pub.dev/documentation/dart_vlc_ffi/latest/dart_vlc_ffi/PlaylistMode-class.html) enum. Could you please clarify on what's the difference between the loop and repeat mode?

**Comment by alexmercerind** [comment]
This is something that is infact confusing about this project,

VLC has following playlist modes:
https://videolan.videolan.me/vlc/group__libvlc__media__list__player.html#ga1f0139f9220d7578fab37a3c1a74af9c

Since, `default` was a Dart keyword, I had to replace it with `single` (which possibly  isn't a correct word to describe). Let me know, if you want to change it to something else more descriptive.
